### ISSUE TITLE
I'm only getting a single item in the menu

### ISSUE THREAD

**Issue by Melindrea** [criticalmash/assemble-navigation#16]
So, nice work! I like this thing a lot.

However ... I can't get it to work properly. 

relevant bits of code:
```
var navigation = new Navigation({
  'menus': ['main', 'footer'],
  'default': 'main'
});

app.onLoad(/./, navigation.onLoad());
app.preRender(/./, navigation.preRender());
```

I have `navigation.clearMenus();` as the initial part of my build step

In several templates (this is just the index example):
```
menu:
    - main
menu-title: Home
```

However, in each of the page-menus, I only get the page that's active, not the other pages. What am I missing?

**Comment by criticalmash** [comment]
Hi @Melindrea thanks for trying out Assemble Navigation.

Most likely, individual pages are being written out before all the views (home, about, etc.) are loaded, leaving you with an incomplete menu. You need to pause the stream between the `onLoad` and `preRender` events and wait for all your views to load before proceeding.

Here's the sample task from the README...

```js
/* a sample task */
app.task('content', function () {
  /* clear out any old data (important during development) */
  navigation.clearMenus();
  /* `src/content` would be designated as the cwd */
  app.pages('src/content/**/*.{md,hbs}'); /* load all content and buffer */
  return app.toStream('pages')  /* restart the stream */
    .pipe(app.renderFile())
    .on('err', console.error)
    .pipe(extname())
    .pipe(app.dest('build'));
});
```

Notice the line containing `app.pages`, this is telling Assemble to load all the template files and to wait until they have all been loaded, parsed and buffered. Behind the scenes, Navigation is reading each file as it streams in and adding it's data to the `navigation` object.

Once we have all the data, we start the stream running again with `app.toStream` and pipe the contents of the buffer into `app.renderFile`. At this point, Navigation runs it's `preRender` function and adds a localized navigation object to each view before rendering.

I hope this helps, if not include the entire copy of your build step and I give a look over.

Good luck!

**Comment by Melindrea** [comment]
Alright, moving it helped with create it correctly (it seems), but I'm getting a "nice" error in the end ...

```
<--- Last few GCs --->

   38712 ms: Scavenge 1390.4 (1458.1) -> 1390.4 (1458.1) MB, 0.6 / 0 ms [allocation failure].
   38713 ms: Scavenge 1390.4 (1458.1) -> 1390.4 (1458.1) MB, 0.6 / 0 ms [allocation failure].
   39380 ms: Mark-sweep 1390.4 (1458.1) -> 1388.7 (1458.1) MB, 667.8 / 0 ms (+ 2.4 ms in 35 steps since start of marking, biggest step 0.1 ms) [last resort gc].
   40048 ms: Mark-sweep 1388.7 (1458.1) -> 1390.1 (1458.1) MB, 667.2 / 0 ms [last resort gc].


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x209ecee3ac1 <JS Object>
    1: assignValue(aka assignValue) [/Users/blahblhah/projects/antoniusm.se/node_modules/assemble-navigation/node_modules/lodash/lodash.js:~2511] [pc=0x190c79b0c825] (this=0x209ece04189 <undefined>,object=0xdaa2bb20c99 <an Object with map 0x34024a508359>,key=0x3a76d50fcb91 <String[3]: 640>,value=0x2e3a850630d1 <an Object with map 0x2da82f43a811>)
    2: /* anonymous */(aka /* anonymous */)...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory
Abort trap: 6
```

I do have plenty of pages that are created, but not an unreasonable amount

**Comment by criticalmash** [comment]
The largest site I've used this with so far contains 32 pages, and I haven't had any out-of-memory issues.

Is this happening the first time Assemble runs? Or does it occur later on?

**Comment by Melindrea** [comment]
I have a total of ~50, which includes posts, pages, archives (index for my blog + categories + tags). 

It appears, however, that it's the posts themselves that is causing this. I can run it with pages and archives (~40 pages), but if I run only the posts (~10) it gets the out-of-memory.

My posts are written as markdown files, nothing too fancy there

**Comment by Melindrea** [comment]
And since I realise I didn't answer that question: the issue comes as it's trying to build the files, it doesn't even get to the output if the posts are activated

**Comment by criticalmash** [comment]
@Melindrea, thanks for your patience. I'm going to create a new issue, and try to recreate the behavior in one of my projects. Most likely, Navigation isn't cleaning up after itself and is leaking memory. I'm not sure when I'll be getting to it though (I'm dealing with an year-end rush), so prepare to wait.

In the meantime, if you're not going to use blog posts in your main menu. Try setting `menu: false` in the front matter of each blog post. That might help in reducing the size of whatever is eating up all the memory.

Best, John

**Comment by Melindrea** [comment]
Hi there!

Yeah, I completely understand the year-end rush, and I’ll just go back to my old method of building the navigation (I have an external file I’d like to remove).

I tried setting menu:false on the posts, but still no luck.

// AMH

On 26 december 2016 at 15:56:39, criticalmash (notifications@github.com) wrote:

@Melindrea, thanks for your patience. I'm going to create a new issue, and try to recreate the behavior in one of my projects. Most likely, Navigation isn't cleaning up after itself and is leaking memory. I'm not sure when I'll be getting to it though (I'm dealing with an year-end rush), so prepare to wait.

In the meantime, if you're not going to use blog posts in your main menu. Try setting menu: false in the front matter of each blog post. That might help in reducing the size of whatever is eating up all the memory.

Best, John

**Comment by criticalmash** [comment]
Hi @Melindrea, I'm trying to investigate your issue and I have a few quick questions.

Which version of node.js are you using?
What's the file structure for the blog posts like? Are they deeply nested?

FYI: I've created a [project](https://github.com/criticalmash/navStressTest) that assembles a site with a large number (145) of pages. Seems to be running fine. But I'd like to mimic your blog structure in there and see what would happen.

Thanks

**Comment by Melindrea** [comment]
After spending way too long time updating, I now have Node 7.4, with the same issue.

I wouldn’t have thought my blog structure was that odd—I’ve just started (after I last checked this) to have a 2nd level deep, before that it was all core. I do use the permalink module, but that shouldn’t affect things, should it?

Here’s a link to my repo. I _think_ all the tweaks should be in there. The only thing I’ve done to have it not run your mod is that I’ve commented out the loading of the functions fairly high up in assemble.js

To build the HTML (which is what’d be relevant here), just run `assemble build` https://github.com/Melindrea/antoniusm.se


On 14 januari 2017 at 21:13:57, criticalmash (notifications@github.com) wrote:

Hi @Melindrea, I'm trying to investigate your issue and I have a few quick questions.

Which version of node.js are you using?
What's the file structure for the blog posts like? Are they deeply nested?

FYI: I've created a project that assembles a site with a large number (145) of pages. Seems to be running fine. But I'd like to mimic your blog structure in there and see what would happen.

Thanks

**Comment by criticalmash** [comment]
Thanks, I'll try it right now.

**Comment by criticalmash** [comment]
Wow, just ran it without than with navigation activated. Assemble is using 10x the memory when navigation is on. I would have expected memory usage to double at most.

How are you creating the `posts` and `archives` collections? I don't see app.create() calls for them.

**Comment by Melindrea** [comment]
Those are in blog/index.js (i’ve been trying to break things out, and refactor so that I can use modules rather than needing to copy/paste in my next site)


On 14 januari 2017 at 23:09:34, criticalmash (notifications@github.com) wrote:

Wow, just ran it without than with navigation activated. Assemble is using 10x the memory when navigation is on. I would have expected memory usage to double at most.

How are you creating the posts and archives collections? I don't see app.create() calls for them.

**Comment by criticalmash** [comment]
@Melindrea try rewriting your middleware registrations like so

```js
var navigation = new Navigation(config.data.site.nav);
app.pages.onLoad(/./, navigation.onLoad());
app.pages.preRender(/./, navigation.preRender());

app.posts.onLoad(/./, navigation.onLoad());
app.posts.preRender(/./, navigation.preRender());
```

Navigation needs to hook into the events on a collection-by-collection basis. And a collection needs to exist before it can be attached to, so move the code block down the script to past your `app.create('pages)` call. If you want to add archive links, move `app.create('archives')` up out of your blog module and under 'create views collections' so that it exists before middleware config.

Try this out and let me know how it works.

BTW: A very impressive build script. I have yet to figure out how to use `paginationator` myself.

**Comment by Melindrea** [comment]
Okay, woo! Now that works. Next step is going to be to get it to use the proper links--is there a smart way for that as far as you know? (I use `assemble-permalinks`)

And thanks, I've been working on that since ... forever <.< Tweaking, fixing, etc. The pagination was the latest puzzle piece before this navigation.

**Comment by criticalmash** [comment]
Permalink's support is on my list as well. The problem is navigation is created with the `onLoad` event, and `permalinks` are created later on in the pipeline.

If you feel like messing with it, try calling the middleware with different [router methods](https://github.com/assemble/assemble/blob/master/support/docs/src/content/api/middleware.md#router-methods)

like so

```js
app.pages.preRender(/./, navigation.onLoad());
app.pages.preCompile(/./, navigation.preRender());
```

At this point, objects in the stream should have already gone through the permalink function. Though chances are you'll need to buffer the stream between the call to permalink and before the render.

Try that and let me know what happens. ; )

**Comment by Melindrea** [comment]
Sounds like a plan! Will do and see how we can get it to work =)

And yeah, that makes a lot of sense, that it’s an event issue.


On 15 januari 2017 at 00:31:56, criticalmash (notifications@github.com) wrote:

Permalink's support is on my list as well. The problem is navigation is created with the onLoad event, and permalinks are created later on in the pipeline.

If you feel like messing with it, try calling the middleware with different [router methods] (https://github.com/assemble/assemble/blob/master/support/docs/src/content/api/middleware.md#router-methods)

like so

pp.pages.preRender(/./, navigation.onLoad());
app.pages.preCompile(/./, navigation.preRender());
At this point, objects in the stream should have already gone through the permalink function. Though chances are you'll need to buffer the stream between the call to permalink and before the render.

Try that and let me know what happens. ; )

**Comment by criticalmash** [comment]
This issue has been broken down into two separate issues for further work.
